/*
    BD2 - TPI Grupo 19
    Script unificado de creación de base de datos y tablas.
    Base de datos: BD2_TPI_G19

*/

CREATE DATABASE BD2_TPI_G19
    COLLATE Latin1_General_CI_AI;
GO

USE BD2_TPI_G19;
GO

SET DATEFORMAT ymd;
GO

-- USE DBTutorias
-- DROP DATABASE IF EXISTS BD2_TPI_G19;

-- Gaston
GO

CREATE TABLE CLASIFICACIONES
(
    id_clasificacion BIGINT NOT NULL IDENTITY(1, 1),
    descripcion NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_CLASIFICACIONES PRIMARY KEY (id_clasificacion)
);
GO

CREATE TABLE GENEROS
(
    id_genero BIGINT NOT NULL IDENTITY(1, 1),
    descripcion NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_GENEROS PRIMARY KEY (id_genero)
);
GO

CREATE TABLE PELICULAS
(
    id_pelicula BIGINT NOT NULL IDENTITY(1, 1),
    id_clasificacion BIGINT NOT NULL,
    id_genero BIGINT NOT NULL,
    titulo NVARCHAR(150) NOT NULL,
    sinopsis NVARCHAR(1000) NULL,
    duracion_minutos SMALLINT NULL,
    CONSTRAINT PK_PELICULAS PRIMARY KEY (id_pelicula),
    CONSTRAINT FK_PELICULAS_CLASIFICACION
        FOREIGN KEY (id_clasificacion) REFERENCES CLASIFICACIONES (id_clasificacion),
    CONSTRAINT FK_PELICULAS_GENERO
        FOREIGN KEY (id_genero) REFERENCES GENEROS (id_genero)
);
GO

-- Gisela

CREATE TABLE COMPLEJOS
(
    id_complejo BIGINT NOT NULL IDENTITY(1, 1),
    nombre NVARCHAR(100) NOT NULL,
    direccion NVARCHAR(255) NOT NULL,
    telefono VARCHAR(50) NULL,
    CONSTRAINT PK_COMPLEJOS PRIMARY KEY (id_complejo)
);
GO

CREATE TABLE SALAS
(
    id_sala BIGINT NOT NULL IDENTITY(1, 1),
    id_complejo BIGINT NOT NULL,
    nombre_sala NVARCHAR(50) NOT NULL,
    capacidad_total SMALLINT NOT NULL,
    tipo_sala VARCHAR(10) NOT NULL,
    CONSTRAINT PK_SALAS PRIMARY KEY (id_sala),
    CONSTRAINT FK_SALAS_COMPLEJOS
        FOREIGN KEY (id_complejo) REFERENCES COMPLEJOS (id_complejo),
    CONSTRAINT CK_SALAS_TIPO_SALA CHECK (tipo_sala IN ('2D', '3D', 'IMAX')),
    CONSTRAINT CK_SALAS_CAPACIDAD CHECK (capacidad_total > 0)
);
GO

CREATE TABLE FUNCIONES
(
    id_funcion BIGINT NOT NULL IDENTITY(1, 1),
    id_pelicula BIGINT NOT NULL,
    id_sala BIGINT NOT NULL,
    fecha_hora DATETIME NOT NULL,
    precio_base MONEY NOT NULL,
    CONSTRAINT PK_FUNCIONES PRIMARY KEY (id_funcion),
    CONSTRAINT FK_FUNCIONES_SALAS
        FOREIGN KEY (id_sala) REFERENCES SALAS (id_sala),
    CONSTRAINT FK_FUNCIONES_PELICULAS
        FOREIGN KEY (id_pelicula) REFERENCES PELICULAS (id_pelicula),
    CONSTRAINT CK_FUNCIONES_PRECIO_BASE CHECK (precio_base > 0),
    CONSTRAINT CK_FUNCIONES_FECHA_HORA CHECK (fecha_hora > GETDATE())
);
GO

-- Henry (parte 1)

CREATE TABLE USUARIOS
(
    id_usuario BIGINT NOT NULL IDENTITY(1, 1),
    nombre NVARCHAR(100) NOT NULL,
    apellido NVARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    fecha_registro DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT PK_USUARIOS PRIMARY KEY (id_usuario),
    CONSTRAINT UQ_USUARIOS_Email UNIQUE (email)
);
GO

CREATE TABLE BUTACAS
(
    id_butaca BIGINT NOT NULL IDENTITY(1, 1),
    id_sala BIGINT NOT NULL,
    fila VARCHAR(1) NOT NULL,
    numero TINYINT NOT NULL,
    CONSTRAINT PK_BUTACAS PRIMARY KEY (id_butaca),
    CONSTRAINT FK_BUTACAS_SALAS FOREIGN KEY (id_sala) REFERENCES SALAS (id_sala),
    CONSTRAINT CK_BUTACAS_Numero CHECK (numero >= 1),
    CONSTRAINT UQ_BUTACAS_SalaFilaNumero UNIQUE (id_sala, fila, numero)
);
GO

-- Marcelo

CREATE TABLE METODOS_PAGOS
(
    id_metodo_pago BIGINT NOT NULL IDENTITY(1, 1),
    nombre NVARCHAR(50) NOT NULL,
    CONSTRAINT PK_METODOS_PAGOS PRIMARY KEY (id_metodo_pago),
    CONSTRAINT UQ_METODOS_PAGOS_Nombre UNIQUE (nombre)
);
GO

CREATE TABLE RESERVAS
(
    id_reserva BIGINT NOT NULL IDENTITY(1, 1),
    id_usuario BIGINT NOT NULL,
    id_funcion BIGINT NOT NULL,
    fecha_reserva DATETIME NOT NULL DEFAULT GETDATE(),
    total_pagado MONEY NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
    CONSTRAINT PK_RESERVAS PRIMARY KEY (id_reserva),
    CONSTRAINT FK_RESERVAS_USUARIOS FOREIGN KEY (id_usuario) REFERENCES USUARIOS (id_usuario),
    CONSTRAINT FK_RESERVAS_FUNCIONES FOREIGN KEY (id_funcion) REFERENCES FUNCIONES (id_funcion),
    CONSTRAINT CK_RESERVAS_ESTADO CHECK (estado IN ('Pendiente', 'Pagada', 'Cancelada')),
    CONSTRAINT CK_RESERVAS_TOTALPAGADO CHECK (total_pagado IS NULL OR total_pagado >= 0)
);
GO

CREATE TABLE PAGOS
(
    id_pago BIGINT NOT NULL IDENTITY(1, 1),
    id_reserva BIGINT NOT NULL,
    id_metodo_pago BIGINT NOT NULL,
    fecha_pago DATETIME NOT NULL DEFAULT GETDATE(),
    total_pagado MONEY NOT NULL,
    estado_pago VARCHAR(20) NOT NULL DEFAULT 'Pendiente',
    CONSTRAINT PK_PAGOS PRIMARY KEY (id_pago),
    CONSTRAINT FK_PAGOS_RESERVAS FOREIGN KEY (id_reserva) REFERENCES RESERVAS (id_reserva),
    CONSTRAINT FK_PAGOS_METODOS_PAGOS FOREIGN KEY (id_metodo_pago) REFERENCES METODOS_PAGOS (id_metodo_pago),
    CONSTRAINT UQ_PAGOS_RESERVA UNIQUE (id_reserva),
    CONSTRAINT CK_PAGOS_TOTALPAGADO CHECK (total_pagado > 0),
    CONSTRAINT CK_PAGOS_ESTADO CHECK (estado_pago IN ('Pendiente', 'Aprobado', 'Rechazado', 'Devuelto'))
);
GO

-- Henry (parte 2)

CREATE TABLE DETALLES_RESERVAS
(
    id_detalle BIGINT NOT NULL IDENTITY(1, 1),
    id_reserva BIGINT NOT NULL,
    id_butaca BIGINT NOT NULL,
    precio_unitario MONEY NOT NULL,
    CONSTRAINT PK_DETALLES_RESERVAS PRIMARY KEY (id_detalle),
    CONSTRAINT FK_DETALLES_RESERVAS_RESERVAS FOREIGN KEY (id_reserva) REFERENCES RESERVAS (id_reserva),
    CONSTRAINT FK_DETALLES_RESERVAS_BUTACAS FOREIGN KEY (id_butaca) REFERENCES BUTACAS (id_butaca),
    CONSTRAINT CK_DETALLES_RESERVAS_Precio CHECK (precio_unitario >= 0),
    CONSTRAINT UQ_DETALLES_RESERVAS_ReservaButaca UNIQUE (id_reserva, id_butaca)
);
GO

PRINT 'Base de datos BD2_TPI_G19 creada correctamente.';
GO